# Logo (Font Awesome Class)
fa_logo: fa-connectdevelop

# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Tags: /tags
  Categories: /categories
  Contact: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: 
facebook_url: https://www.facebook.com/profile.php?id=100006290353213
instagram_url: https://www.instagram.com/zhaomengxiao/
dribble_url: 
github_url: https://github.com/zhaomengxiao
googleplus_url: 
behance_url: 
fivehundredpx_url: 
email_url: zhaoyoujun324@163.com
rss_url: \#

# Footer About Text
footer_about: "This theme was developed by <a href=\"https://github.com/klugjo\">Jonathan Klughertz</a>. The source code is available on Github. Create Websites. Make Magic."

# Footer Copyright Line
footer_copyright: "@Untitled. All right reserved | Design & Hexo <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"

